### ISSUE TITLE
the result of logsnr_t = vp_logsnr(t, self.beta_d, self.beta_min) was NaN

### ISSUE THREAD

**Issue by SDD2021-car** [alexzhou907/DDBM#13]
The parameters I used like the picture below. 
<img width="179" alt="屏幕截图 2024-11-07 104849" src="https://github.com/user-attachments/assets/ec4b7746-4ca6-403b-b052-ee7a8cda2650">
But I found the result of logsnr_t = vp_logsnr(t, self.beta_d, self.beta_min)  was NaN, because the result of 
<img width="290" alt="屏幕截图 2024-11-07 105016" src="https://github.com/user-attachments/assets/7e83ecb2-c8a0-4b03-8bcd-cd63ebb642a1">
is inf. I'm confused about what caused this. Thanks.

**Comment by SMU-Lkx** [comment]
Hello, I have also encountered a similar issue where the value of 'inf' appears. Do you know the reason?
